import '../../src/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import {MyContextProvider} from './components/mycontext'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <MyContextProvider>
        <div className='flex justify-start   '>
      <Navbar />
      {children}
      </div>
      </MyContextProvider></body>
    </html>
  )
}
